backend:
  name: github
  repo: hamudi2012/mj-home
  branch: main
  auth_type: token

media_folder: public/images/products
public_folder: images/products

collections:
  - name: "shops"
    label: "🛍️ MJ Shops"
    folder: "src/data/shops"
    create: true
    slug: "{{slug}}"
    extension: json
    format: json
    fields:
      - { label: "Nama", name: "nama", widget: "string" }
      - { label: "Harga", name: "harga_diskon", widget: "number" }
      - { label: "Foto", name: "foto", widget: "image" }

  - name: "food"
    label: "🍜 MJ Food"
    folder: "src/data/food"
    create: true
    slug: "{{slug}}"
    extension: json
    format: json
    fields:
      - { label: "Nama", name: "nama", widget: "string" }
      - { label: "Harga", name: "harga", widget: "number" }
      - { label: "Foto", name: "foto", widget: "image" }

  - name: "news"
    label: "📰 MJ News"
    folder: "src/data/news"
    create: true
    slug: "{{slug}}"
    extension: json
    format: json
    fields:
      - { label: "Judul", name: "judul", widget: "string" }
      - { label: "Konten", name: "konten", widget: "text" }
      - { label: "Foto", name: "foto", widget: "image" }
      
