backend:
  name: test-repo
  branch: main
  api_root: https://api.github.com/repos/hamudi2012/mj-home/git

media_folder: public/images/products
public_folder: /mj-home/images/products

collections:
  - name: "products"
    label: "Produk MJ Shops"
    folder: "src/data"
    create: true
    slug: "{{slug}}"
    extension: json
    format: json
    fields:
      - { label: "ID", name: "id", widget: "number", required: false }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Nama Produk", name: "nama", widget: "string", required: true }
      - { label: "Harga Asli", name: "harga_asli", widget: "number", required: false }
      - { label: "Harga Diskon", name: "harga_diskon", widget: "number", required: true }
      - { label: "Kategori", name: "kategori", widget: "list", default: ["fashion"] }
      - { label: "Ukuran", name: "ukuran", widget: "list", default: ["M", "L", "XL"] }
      - { label: "Warna", name: "warna", widget: "list", default: ["Hitam"] }
      - { label: "Stok", name: "stok", widget: "number", default: 10 }
      - { label: "Deskripsi", name: "deskripsi", widget: "text" }
      - { label: "Foto Utama", name: "foto", widget: "image" }
      - { label: "Galeri", name: "foto_gallery", widget: "list", default: [] }
      - { label: "Rating", name: "rating", widget: "number", default: 4.5 }
      - { label: "Terjual", name: "terjual", widget: "number", default: 0 }
      - { label: "Tags", name: "tags", widget: "list", default: ["new"] }
